@startuml erd
left to right direction

class Skilt {
    Skiltenummer
    Navn
    Niveau
    Ikon
    Tegning
    }
class Bruger {
    Navn
    Rolle
    }
class Rallybane {
    Lavet af
    Niveau
    Tema
    Antal skilte
    }

Bruger "1" -- "*" Rallybane
Skilt "10..20" -- "1" Rallybane

hide methods
@enduml